import supabase from '../config/database.js';

class BacklogCommentModel {
  // Get next backlog_commentid by finding max and incrementing
  static async getNextCommentId() {
    const { data, error } = await supabase
      .from('backlog_comments')
      .select('backlog_commentid')
      .order('backlog_commentid', { ascending: false })
      .limit(1)
      .single();

    if (error && error.code !== 'PGRST116') { // PGRST116 = no rows returned
      console.error('Error getting max backlog_commentid:', error);
      return 1; // Default to 1 if error
    }

    const maxId = data?.backlog_commentid || 0;
    return maxId + 1;
  }

  // Create a backlog comment
  static async create(commentData) {
    // Remove backlog_commentid from data if present - it's auto-generated by database
    // According to schema: backlog_commentid integer generated by default as identity not null
    const { backlog_commentid, ...dataToInsert } = commentData;

    // Set timestamps if not provided
    if (!dataToInsert.created_time) {
      dataToInsert.created_time = new Date().toISOString();
    }
    if (!dataToInsert.updated_time) {
      dataToInsert.updated_time = new Date().toISOString();
    }

    // Don't manually set backlog_commentid - let database generate it
    const { data, error } = await supabase
      .from('backlog_comments')
      .insert([dataToInsert])
      .select()
      .single();

    return { data, error };
  }
}

export default BacklogCommentModel;

