import supabase from '../config/database.js';

class BacklogDocumentModel {
  // Get next document_id by finding max and incrementing
  static async getNextDocumentId() {
    const { data, error } = await supabase
      .from('backlog_documents')
      .select('document_id')
      .order('document_id', { ascending: false })
      .limit(1)
      .single();

    if (error && error.code !== 'PGRST116') { // PGRST116 = no rows returned
      console.error('Error getting max document_id:', error);
      return 1; // Default to 1 if error
    }

    const maxId = data?.document_id || 0;
    return maxId + 1;
  }

  // Create a backlog document
  static async create(documentData) {
    // Remove document_id from data if present - it's auto-generated by database
    // According to schema: document_id integer generated always as identity not null
    const { document_id, ...dataToInsert } = documentData;

    // Don't manually set document_id - let database generate it
    const { data, error } = await supabase
      .from('backlog_documents')
      .insert([dataToInsert])
      .select()
      .single();

    return { data, error };
  }

  // Create multiple documents
  static async createMultiple(documentsArray) {
    if (!documentsArray || documentsArray.length === 0) {
      return { data: [], error: null };
    }

    // Remove document_id from each document - it's auto-generated by database
    // According to schema: document_id integer generated always as identity not null
    const documentsWithoutIds = documentsArray.map(doc => {
      const { document_id, ...docWithoutId } = doc;
      return docWithoutId;
    });

    console.log('Documents prepared for insert (without document_id):', documentsWithoutIds.map(d => ({
      backlog_id: d.backlog_id,
      original_filename: d.original_filename,
      category_id: d.category_id
    })));

    // Don't manually set document_id - let database generate it
    const { data, error } = await supabase
      .from('backlog_documents')
      .insert(documentsWithoutIds)
      .select();

    return { data, error };
  }
}

export default BacklogDocumentModel;

